numbers = [1, 2, 3]
print("Без функцій:", numbers) 
numbers.extend([4,5])
print(" extend:", numbers) 
numbers.append(6)
print(" append:", numbers) 
numbers.insert(1,2)
print(" insert:", numbers) 
numbers.remove(2)
print(" remove:", numbers) 
numbers.reverse()
print(" reverse:", numbers) 
numbers.sort()
print(" sort:", numbers) 
numbers.clear()
print(" clear:", numbers) 